# Generated by Django 5.2.15 on 2026-06-27 00:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('flocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(db_index=True, help_text='Stable device identifier reported by the Raspberry Pi', max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('firmware_version', models.CharField(blank=True, max_length=40)),
                ('hardware', models.CharField(blank=True, default='Raspberry Pi', max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('decommissioned', 'Decommissioned')], default='active', max_length=20)),
                ('has_camera', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_demo', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='farms.farm')),
                ('pen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='farms.pen')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='iot.iotdevice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('memory_percent', models.FloatField(blank=True, null=True)),
                ('disk_percent', models.FloatField(blank=True, null=True)),
                ('cpu_temp_c', models.FloatField(blank=True, null=True)),
                ('uptime_seconds', models.BigIntegerField(blank=True, null=True)),
                ('queued_records', models.IntegerField(default=0)),
                ('firmware_version', models.CharField(blank=True, max_length=40)),
                ('device_timestamp', models.DateTimeField(blank=True, null=True)),
                ('server_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='iot.iotdevice')),
            ],
            options={
                'ordering': ['-server_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sampling_interval_seconds', models.PositiveIntegerField(default=60)),
                ('heartbeat_interval_seconds', models.PositiveIntegerField(default=120)),
                ('capture_interval_seconds', models.PositiveIntegerField(default=300)),
                ('inference_enabled', models.BooleanField(default=True)),
                ('confidence_threshold', models.FloatField(default=0.35)),
                ('frame_skip', models.PositiveIntegerField(default=5)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='iot.iotdevice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActuatorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('actuator', models.CharField(choices=[('fan', 'Fan'), ('heater', 'Heater'), ('light', 'Light'), ('water', 'Water valve'), ('feeder', 'Feeder')], max_length=20)),
                ('new_state', models.BooleanField()),
                ('trigger', models.CharField(blank=True, help_text='e.g. threshold, manual', max_length=80)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('device_timestamp', models.DateTimeField(blank=True, null=True)),
                ('server_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuator_events', to='farms.farm')),
                ('pen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.pen')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuator_events', to='iot.iotdevice')),
            ],
            options={
                'ordering': ['-server_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('humidity_pct', models.FloatField(blank=True, null=True)),
                ('raw_gas_value', models.FloatField(blank=True, help_text='Raw MQ ADC reading (uncalibrated)', null=True)),
                ('gas_risk_value', models.FloatField(blank=True, help_text='Processed relative air-quality / ammonia-risk (0-1)', null=True)),
                ('gas_risk_category', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=10)),
                ('fan_state', models.BooleanField(default=False)),
                ('heater_state', models.BooleanField(default=False)),
                ('sensor_status', models.CharField(blank=True, default='ok', max_length=40)),
                ('quality', models.CharField(choices=[('good', 'Good'), ('suspect', 'Suspect'), ('rejected', 'Rejected')], default='good', max_length=10)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('device_timestamp', models.DateTimeField(blank=True, null=True)),
                ('server_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='flocks.batch')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='iot.iotdevice')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='farms.farm')),
                ('pen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.pen')),
            ],
            options={
                'ordering': ['-server_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('record_type', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('duplicate', 'Duplicate'), ('rejected', 'Rejected')], default='accepted', max_length=20)),
                ('target_uuid', models.UUIDField(blank=True, null=True)),
                ('device_timestamp', models.DateTimeField(blank=True, null=True)),
                ('server_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_records', to='iot.iotdevice')),
            ],
            options={
                'ordering': ['-server_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('temp_min_c', models.FloatField(default=18.0)),
                ('temp_max_c', models.FloatField(default=32.0)),
                ('humidity_min_pct', models.FloatField(default=40.0)),
                ('humidity_max_pct', models.FloatField(default=75.0)),
                ('gas_risk_warning', models.FloatField(default=0.5, help_text='Relative gas-risk value (0-1) for a warning')),
                ('gas_risk_critical', models.FloatField(default=0.8, help_text='Relative gas-risk value (0-1) for a critical alert')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='farms.farm')),
                ('pen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='farms.pen')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['farm', 'pen'],
                'unique_together': {('farm', 'pen')},
            },
        ),
        migrations.AddIndex(
            model_name='iotdevice',
            index=models.Index(fields=['farm', 'status'], name='iot_iotdevi_farm_id_13d395_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceheartbeat',
            index=models.Index(fields=['device', 'server_timestamp'], name='iot_deviceh_device__5a39a9_idx'),
        ),
        migrations.AddIndex(
            model_name='actuatorevent',
            index=models.Index(fields=['device', 'server_timestamp'], name='iot_actuato_device__81b043_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['device', 'server_timestamp'], name='iot_sensorr_device__d28f11_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['pen', 'server_timestamp'], name='iot_sensorr_pen_id_cee6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['gas_risk_category'], name='iot_sensorr_gas_ris_6c86cd_idx'),
        ),
    ]
