# Generated by Django 5.2.15 on 2026-06-27 00:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('flocks', '0001_initial'),
        ('iot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('model_name', models.CharField(default='yolo11n', max_length=80)),
                ('model_version', models.CharField(blank=True, max_length=60)),
                ('predicted_class', models.CharField(db_index=True, max_length=60)),
                ('confidence', models.FloatField(default=0.0)),
                ('risk_category', models.CharField(blank=True, db_index=True, max_length=60)),
                ('severity', models.CharField(blank=True, max_length=10)),
                ('detection_count', models.PositiveIntegerField(default=0)),
                ('detections', models.JSONField(blank=True, default=list, help_text='List of {class, confidence, bbox:[x,y,w,h]} from the model')),
                ('image_reference', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vision/%Y/%m/')),
                ('device_timestamp', models.DateTimeField(blank=True, null=True)),
                ('server_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('review_status', models.CharField(choices=[('pending', 'Pending review'), ('accepted', 'Accepted'), ('corrected', 'Corrected'), ('uncertain', 'Marked uncertain'), ('false', 'False alert'), ('escalated', 'Escalated')], db_index=True, default='pending', max_length=20)),
                ('corrected_class', models.CharField(blank=True, max_length=60)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vision_results', to='flocks.batch')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vision_results', to='iot.iotdevice')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_results', to='farms.farm')),
                ('pen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.pen')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vision_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-server_timestamp'],
                'indexes': [models.Index(fields=['farm', 'server_timestamp'], name='vision_visi_farm_id_f0bc73_idx'), models.Index(fields=['predicted_class', 'server_timestamp'], name='vision_visi_predict_90692c_idx'), models.Index(fields=['review_status'], name='vision_visi_review__dec456_idx')],
            },
        ),
    ]
