# Generated by Django 5.2.15 on 2026-06-27 00:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('flocks', '0001_initial'),
        ('iot', '0001_initial'),
        ('vision', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('high_temp', 'High temperature'), ('low_temp', 'Low temperature'), ('high_humidity', 'High humidity'), ('low_humidity', 'Low humidity'), ('high_gas', 'High gas risk'), ('sensor_failure', 'Sensor failure'), ('camera_failure', 'Camera failure'), ('device_offline', 'Device offline'), ('visible_distress', 'Possible visible distress'), ('lethargy', 'Lethargy'), ('open_beak_stress', 'Open-beak stress'), ('diseased_eye', 'Diseased eye'), ('mobility_abnormality', 'Mobility abnormality'), ('physical_abnormality', 'Visible physical abnormality'), ('huddling', 'Huddling'), ('unusual_mortality', 'Unusual mortality'), ('low_stock', 'Low stock'), ('missed_vaccination', 'Missed vaccination'), ('sync_failure', 'Synchronisation failure')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, max_length=10)),
                ('source', models.CharField(choices=[('sensor', 'Sensor'), ('vision', 'Vision'), ('system', 'System'), ('manual', 'Manual')], default='system', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('investigating', 'Under investigation'), ('resolved', 'Resolved'), ('false', 'False alert'), ('escalated', 'Escalated')], db_index=True, default='new', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('last_triggered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('trigger_count', models.PositiveIntegerField(default=1)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='flocks.batch')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='iot.iotdevice')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='farms.farm')),
                ('pen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.pen')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('sensor_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iot.sensorreading')),
                ('vision_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='vision.visionresult')),
            ],
            options={
                'ordering': ['-last_triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='alerts.alert')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_critical', models.BooleanField(default=True)),
                ('email_warning', models.BooleanField(default=False)),
                ('in_app', models.BooleanField(default=True)),
                ('min_severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'severity'], name='alerts_aler_status_58cd09_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['farm', 'status'], name='alerts_aler_farm_id_f4ff35_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'status'], name='alerts_aler_alert_t_82e8cd_idx'),
        ),
    ]
